---
deployment:
  tasks:
    - sh ~/public_html/vishwjeet-client/deploy1.sh 2>&1
    - export DEPLOYPATH=~/public_html/
    - /bin/cp -R ~/repositories/vishwjeet-client/ $DEPLOYPATH
    - sh ~/public_html/vishwjeet-client/deploy.sh 2>&1
    